import pygame

FPS = 600
WIN_WIDTH = 960
WIN_HEIGHT = 960
SCREEN = pygame.display.set_mode((WIN_HEIGHT, WIN_WIDTH))
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

WORKSPACE_RADIUS = 470
# gear config

GEAR_RADIUS = 200
LINEAR_SPEED = 1  # set speed for draw_dot
GEAR_ANGLE_VELOCITY = LINEAR_SPEED / (WORKSPACE_RADIUS - GEAR_RADIUS)
# draw_dot config

DOT_RADIUS = 200
DOR_COLOR = WHITE
DOT_ANGLE_VELOCITY = GEAR_ANGLE_VELOCITY * (WORKSPACE_RADIUS / GEAR_RADIUS)
